.SUFFIXES: .o .c

CC = cxx 
#gcc
CFLAGS = -g3 -D_REENTRANT
LFLAGS = -lm -lpthread

CTAGS =     ctags
BIN = gauss
CFILES =   gauss.c
OBJECTS =  gauss.o
HFILES = 
OTHERSOURCES =  
SOURCES =   $(HFILES) $(CFILES) $(OTHERSOURCES)

.c.o:  
	$(CC) -c $(CFLAGS) $*.c

$(BIN): $(OBJECTS)
	$(CC) $(LFLAGS) -o $(BIN) $(OBJECTS)

tags: $(CFILES) $(HFILES) $(EXTRACTCFILES) $(RECOGCFILES)
# for vi:
	$(CTAGS) -d -t -T -w $(CFILES) $(HFILES) 
	sort -o tags tags

clean:
	-rm $(BIN) $(OBJECTS) 

